server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
db-verify:
  target-confirmed-variables:
    - innodb_adaptive_hash_index
    - performance_schema_show_processlist
    - performance_schema
    - performance_schema_accounts_size
    - performance_schema_digests_size
    - performance_schema_error_size
    - performance_schema_events_stages_history_long_size
    - performance_schema_events_stages_history_size
    - performance_schema_events_statements_history_long_size
    - performance_schema_events_statements_history_size
    - performance_schema_events_transactions_history_long_size
    - performance_schema_events_transactions_history_size
    - performance_schema_events_waits_history_long_size
    - performance_schema_events_waits_history_size
    - performance_schema_hosts_size
    - performance_schema_max_cond_classes
    - performance_schema_max_cond_instances
    - performance_schema_max_digest_length
    - performance_schema_max_file_classes
    - performance_schema_max_file_handles
    - performance_schema_max_file_instances
    - performance_schema_max_index_stat
    - performance_schema_max_memory_classes
    - performance_schema_max_metadata_locks
    - performance_schema_max_mutex_classes
    - performance_schema_max_mutex_instances
    - performance_schema_max_prepared_statements_instances
    - performance_schema_max_program_instances
    - performance_schema_max_rwlock_classes
    - performance_schema_max_rwlock_instances
    - performance_schema_max_socket_classes
    - performance_schema_max_socket_instances
    - performance_schema_max_sql_text_length
    - performance_schema_max_stage_classes
    - performance_schema_max_statement_classes
    - performance_schema_max_statement_stack
    - performance_schema_max_table_handles
    - performance_schema_max_table_instances
    - performance_schema_max_table_lock_stat
    - performance_schema_max_thread_classes
    - performance_schema_max_thread_instances
    - performance_schema_session_connect_attrs_size
    - performance_schema_setup_actors_size
    - performance_schema_setup_objects_size
    - performance_schema_users_size
    - admin_ssl_ca
    - admin_ssl_capath
    - admin_ssl_cert
    - admin_ssl_cipher
    - admin_ssl_crl
    - admin_ssl_crlpath
    - admin_ssl_key
    - admin_tls_ciphersuites
    - admin_tls_version
    - max_connections
    - max_binlog_size
    - ssl_ca
    - ssl_cert
    - ssl_key
    - system_time_zone
    - time_zone

